import type { Athlete } from "@/lib/types";

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  KINETIC EDGE ATHLETES — VERIFIED RESULTS ONLY
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Every name, sport, placing, category, competition and year below is read off
 * the congratulation posters supplied by the client on 25 Sep 2026. Nothing has
 * been rounded up, renamed or inferred beyond what those posters state, and the
 * photographs are crops of the athletes' own photos from the same posters.
 *
 * RULES
 * • Never invent or upgrade a result, add a year the source does not state, or
 *   attach a competition an athlete did not compete in.
 * • Never aggregate these into medal totals, athlete counts or success rates.
 * • Alt text is GENERATED by `athleteAlt()` from these fields — never write it
 *   by hand. That is what guarantees one athlete is never described with
 *   another athlete's result.
 * • The first achievement is the one shown on the card, so list the strongest
 *   first; the rest appear in the athlete's profile.
 *
 * ⚠ ONE INFERENCE TO CONFIRM: Sugi Sai's poster does not print a sport. It is
 * recorded as Badminton because the Czech International Future Series is a
 * badminton tournament and he is in badminton kit in the photograph. Correct it
 * here if that is wrong.
 */
export const athletes: Athlete[] = [
  {
    slug: "anushree",
    name: "Anushree",
    sport: "Badminton",
    image: { src: "/images/athletes/anushree.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Winner",
        category: "U-17 Girls Singles",
        competition: "Qatar Badminton Association, Leg-I",
        year: "2026",
      },
      {
        result: "Winner",
        category: "U-17 Girls Doubles",
        competition: "Qatar Badminton Association, Leg-I",
        year: "2026",
      },
    ],
  },
  {
    slug: "dheeshitha",
    name: "Dheeshitha",
    sport: "Badminton",
    image: { src: "/images/athletes/dheeshitha.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Gold",
        category: "Girls Doubles",
        competition: "U-17 Badminton State Ranking",
      },
      {
        result: "Silver",
        category: "Mixed Doubles",
        competition: "U-17 Badminton State Ranking",
      },
      {
        result: "Bronze",
        category: "Girls Doubles",
        competition: "Tamilnadu Junior State Championships",
      },
    ],
  },
  {
    slug: "sugi-sai",
    name: "Sugi Sai",
    sport: "Badminton",
    image: { src: "/images/athletes/sugi-sai.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Bronze",
        category: "Men's Singles",
        competition: "Czech International Future Series",
        year: "2026",
      },
    ],
  },
  {
    slug: "shriya-anand",
    name: "Shriya Anand",
    sport: "Table Tennis",
    image: { src: "/images/athletes/shriya-anand.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Bronze",
        category: "U-19",
        competition: "WTT Youth Contender, Amman",
      },
    ],
  },
  {
    slug: "shahid-ibrahim",
    name: "Shahid Ibrahim",
    sport: "Badminton",
    image: { src: "/images/athletes/shahid-ibrahim.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Silver",
        category: "Mixed Doubles",
        competition: "U-17 Badminton State Ranking",
      },
      {
        result: "Bronze",
        category: "Boys Doubles",
        competition: "U-17 Badminton State Ranking",
      },
    ],
  },
  {
    slug: "farhaan-khan",
    name: "Farhaan Khan",
    sport: "Badminton",
    image: { src: "/images/athletes/farhaan-khan.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Bronze",
        category: "Chennai Men's Team",
        competition: "Tamilnadu Senior State Inter District Team Championships",
        year: "2026",
      },
    ],
  },
  {
    slug: "nandhinee",
    name: "Nandhinee",
    sport: "Cycling",
    image: { src: "/images/athletes/nandhinee.webp", width: 900, height: 1125 },
    achievements: [
      {
        result: "Runner Up",
        category: "Elite Women, Road Race",
        competition: "District Regional Championship",
        year: "2026",
      },
    ],
  },
];

/** Sports represented, in the order they first appear. Derived, never counted by hand. */
export const athleteSports = Array.from(new Set(athletes.map((a) => a.sport)));

/**
 * Alt text, derived from the verified fields. Describes who is in the
 * photograph and nothing else — the achievements sit in the markup beside it,
 * where a screen reader will read them as text.
 */
export function athleteAlt(athlete: Athlete): string {
  return `${athlete.name}, ${athlete.sport.toLowerCase()} athlete at Kinetic Edge`;
}

/** The line a card leads with. */
export function headlineAchievement(athlete: Athlete) {
  return athlete.achievements[0];
}
